imports = ["layout.toml"]

[bar]
scale = 0.83
inset-edge = 0.125
inset-ends = 0.125
bg = "bg-base"
button-variant = "basic"
button-icon-size = 0.85
button-border-location = "none"
dropdown-shadow = false
padding-ends = 1
module-gap = 1

[general]
font-sans = "JetBrainsMono Nerd Font"
font-mono = "JetBrainsMono Nerd Font"

[styling.palette]
bg = "#141415"
elevated = "#252530"
surface = "#252530"
fg = "#cdcdcd"
primary = "#d8647e"
red = "#d8647e"
yellow = "#f3be7c"
green = "#7fa563"
blue = "#bb9dbd"

[modules.clock]
format = "%d/%m/%Y %H:%M:%S"
icon-name = "md-calendar_month-symbolic"
button-bg-color = "bg-base"
label-color = "fg-default"

[modules.hyprland-workspaces]
display-mode = "icon"
min-workspace-count = 3
icon-size = 0.8
container-bg-color = "bg-base"
empty-color = "bg-surface"
occupied-color = "#606079"
active-indicator = "underline"

[modules.hyprland-workspaces.workspace-map]
99 = { icon = "si-spotify" }
98 = { icon = "si-discord" }
97 = { icon = "md-videogame_asset-symbolic" }
96 = { icon = "si-steam" }
1 = { icon = "tbf-circle-symbolic" }
2 = { icon = "tbf-circle-symbolic" }
3 = { icon = "tbf-circle-symbolic" }

[modules.keyboard-input]
icon-color = "accent"
label-color = "fg-default"
button-bg-color = "bg-base"
icon-name = "md-keyboard-symbolic"

[modules.keyboard-input.layout-alias-map]
Polish = "PL"
"Ukrainian (phonetic)" = "UA"
"English (US, intl., with dead keys)" = "US"

[modules.media]
button-bg-color = "bg-elevated"
icon-name = "si-spotify"
icon-type = "default"
players-ignored = ["*mozilla*", "*firefox*", "*zen*"]
player-priority = ["*spotify*"]
icon-color = "accent"
label-color = "fg-default"
middle-click = "playerctl next -p spotify"
right-click = "playerctl play-pause -p spotify"
scroll-up = "playerctl volume 0.1+ -p spotify"
scroll-down = "playerctl volume 0.1- -p spotify"

[modules.volume]
icon-color = "accent"
label-color = "fg-default"
button-bg-color = "bg-base"
scroll-up = "wayle audio output-volume +5"
scroll-down = "wayle audio output-volume -5"
icon-muted = "md-volume_off-symbolic"
level-icons = [
  "md-volume_mute-symbolic",
  "md-volume_down-symbolic",
  "md-volume_up-symbolic"
]

[modules.weather]
location = "Wroclaw, Poland"
button-bg-color = "bg-base"
label-color = "fg-default"
icon-name = "md-sunny-symbolic"
time-format = "24h"
refresh-interval-seconds = 300

[modules.window-title]
format = "{{ app }}"
icon-color = "accent"
button-bg-color = "bg-base"
label-color = "fg-default"
icon-name = "md-window-symbolic"

[modules.notifications]
popup-position = "bottom-right"
popup-max-visible = 3
popup-duration = 4000
popup-shadow = false

[modules.network]
label-color = "fg-default"
button-bg-color = "bg-base"
icon-color = "accent"

[modules.battery]
icon-color = "accent"
icon-bg-color = "bg-base"
label-color = "fg-default"
button-bg-color = "bg-base"

# see https://wayle.app/guide/custom-modules#watch-mode-event-driven-volume-control
[[modules.custom]]
id = "volume-output"
mode = "watch"
restart-policy = "on-exit"
command = '''
emit_state() {
    out=$(pactl get-default-sink)
    out=$([[ "$out" == *hdmi* ]] && echo "speaker" || echo "headphone")
    printf '{"alt": "%s"}\n' "$out"
}
emit_state
pactl subscribe | while read -r line; do
    case "$line" in *sink*) emit_state ;; esac
done
'''
left-click = "switch-audio"
format = ""
icon-map = {
  speaker = "md-speaker-symbolic",
  headphone = "md-headphones-symbolic"
}
button-bg-color = "bg-base"

[osd]
enabled = false
