-- GLOBAL VARIABLES
terminal = "foot"
terminal_class = "foot"
file_manager = "thunar"
file_manager_class = "thunar"
browser = "zen-beta"
browser_class = "zen-beta"
discord = "discord"
discord_class = "discord"
spotify = "spotify"
spotify_class = "Spotify"
mail = "thunderbird"

local ws_spotify = "99"
local ws_discord = "98"
local ws_gaming = "97"
local ws_steam = "96"
local ws_mail = "3"
local ws_terminal = "2"
local ws_browser = "1"

-- generated by config.oliwia.hyprland in nixos configuration
-- defines monitors; important to source it here
dofile("/etc/hypr/monitors.lua")

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################
hl.window_rule({
	name = "...",
	suppress_event = "maximize",
	match = {
		class = ".*",
	},
})

hl.window_rule({
	name = "fullscreen-color",
	border_color = "rgb(6e94b2)",
	match = {
		fullscreen = 1,
	},
})

-- basic
hl.window_rule({
	name = "browser",
	monitor = os.getenv("MAIN_DISPLAY"),
	workspace = ws_browser,
	match = {
		class = string.format("^(%s)$", browser_class),
	},
})
hl.window_rule({
	name = "terminal",
	monitor = os.getenv("MAIN_DISPLAY"),
	workspace = ws_terminal,
	match = {
		class = string.format("^(%s)$", terminal_class),
	},
})
hl.window_rule({
	name = "mail",
	monitor = os.getenv("MAIN_DISPLAY"),
	workspace = ws_mail,
	match = {
		class = string.format("^(%s)$", mail),
	},
})

-- floating autostartup windows are weird and can open up anywhere it feels like
-- spotify
hl.workspace_rule({ workspace = ws_spotify, default_name = "spotify" })
hl.window_rule({
	name = "spotify",
	workspace = ws_spotify,
	monitor = os.getenv("MAIN_DISPLAY"),
	float = true,
	size = "(monitor_w*0.8) (monitor_h*0.85)",
	center = true,
	match = {
		class = string.format("^(%s)$", spotify_class),
	},
})

-- discord - bind to second display (SECOND_DISPLAY points to MAIN_DISPLAY on one monitor hosts)
hl.workspace_rule({
	workspace = "ws_discord",
	default_name = "discord",
	monitor = os.getenv("SECOND_DISPLAY"),
})
hl.window_rule({
	name = "discord",
	workspace = ws_discord,
	monitor = os.getenv("SECOND_DISPLAY"),
	float = true,
	size = "(monitor_w*0.9) (monitor_h*0.85)",
	center = true,
	match = {
		class = string.format("^(%s)$", discord_class),
	},
})

-- steam
hl.workspace_rule({ workspace = ws_steam, default_name = "steam" })
hl.window_rule({
	name = "steam",
	monitor = os.getenv("MAIN_DISPLAY"),
	workspace = ws_steam,
	match = {
		class = "^(steam)$",
	},
})
-- gaming
local games_regex = "steam_app.*|cs2|Minecraft.*|.*Prism.*"
hl.workspace_rule({ workspace = ws_gaming, default_name = "gaming" })
hl.window_rule({
	name = "gaming",
	monitor = os.getenv("MAIN_DISPLAY"),
	workspace = ws_gaming,
	match = {
		class = string.format("^(%s)$", games_regex),
	},
})

--################
--## AUTOSTART ###
--################
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("uwsm app -- wayle panel start")
	hl.exec_cmd("uwsm app -- hyprpaper")
	hl.exec_cmd("uwsm app -- wl-paste --watch cliphist store")
	hl.exec_cmd("uwsm app -- " .. terminal)
	hl.exec_cmd("uwsm app -- " .. browser)
end)
--##################
--## KEYBINDINGS ###
--##################

hl.config({
	binds = {
		allow_workspace_cycles = true,
		scroll_event_delay = 0,
	},
})

local main_mod = "SUPER"
local dsp = hl.dsp
local window = dsp.window

local function bind(keys, what, main)
	main = main or true
	local lhs = main and main_mod .. " + " .. keys or keys
	hl.bind(lhs, what)
end

local function bind_run(keys, cmd, main)
	bind(keys, dsp.exec_cmd(cmd), main)
end

local function bind_focus_or_launch(keys, what)
	local cmd = string.format("focus-or-launch %s %s", _G[what], _G[what .. "_class"])
	bind_run(keys, cmd)
end

bind("Q", window.close({ window = "activewindow" }))
bind("SHIFT + Q", window.kill({ window = "activewindow" }))
bind("ESCAPE", dsp.exec_cmd("uwsm stop"))
bind("F", window.fullscreen({ mode = 1 }))
bind("SHIFT + F", window.fullscreen({ mode = 0 }))
bind("Tab", dsp.focus({ workspace = "previous" }))
bind("R", window.float({ action = "toggle" }))

-- apps
bind_focus_or_launch("E", "file_manager")
bind_focus_or_launch("T", "terminal")
bind_focus_or_launch("B", "browser")
bind_focus_or_launch("D", "discord")
bind_focus_or_launch("S", "spotify")
bind_run("SHIFT + T", terminal)
bind_run("SHIFT + B", browser)
bind_run("SHIFT + D", discord)

bind_run("SHIFT + C", "hyprpicker --autocopy")
bind_run("F1", "switch-audio")

-- screenshots
bind_run("SHIFT + S", "screenshot region")
bind_run("Print", "screenshot screen", false)
bind_run("SHIFT + O", "pinta-clipboard")
bind_run("CTRL + S", "image-to-text")

-- menu stuff
bind_run("SPACE", "rofi -show combi -combi-modes drun,window,power_menu -show-icons -run-command 'uwsm app -- {cmd}'")
bind_run("C", 'rofi -show calc -theme-str "window {width: 30%;}"')
bind_run("V", "rofi-clipboard")
bind_run("SHIFT + M", "rofi -show power-menu -modi power-menu:rofi-power-menu")
bind_run("O", 'rofi-open-filetype "pdf,png,jpeg,jpg,svg,mp4,mov,gif,heic"')
bind_run("U", "rofi-tr")

-- Move focus with mainMod + arrow keys
bind("h", dsp.focus({ direction = "l" }))
bind("l", dsp.focus({ direction = "r" }))
bind("k", dsp.focus({ direction = "u" }))
bind("j", dsp.focus({ direction = "d" }))
bind("SHIFT + h", window.move({ direction = "l" }))
bind("SHIFT + l", window.move({ direction = "r" }))
bind("SHIFT + k", window.move({ direction = "u" }))
bind("SHIFT + j", window.move({ direction = "d" }))

for i = 1, 9 do
	bind(tostring(i), dsp.focus({ workspace = tostring(i) }))
	bind("SHIFT + " .. i, window.move({ workspace = tostring(i) }))
end
bind("0", dsp.focus({ workspace = ws_discord }))
bind("SHIFT + 0", window.move({ workspace = ws_discord }))
bind("G", dsp.focus({ workspace = ws_gaming }))
bind("SHIFT + G", window.move({ workspace = ws_gaming }))

-- move/resize windows with mainMod + LMB/RMB and dragging
bind("mouse:272", window.drag(), { mouse = true })
bind("mouse:273", window.resize(), { mouse = true })

bind_run("mouse:275", "playerctl play-pause -p spotify")
bind_run("P", "playerctl play-pause -p spotify")
bind_run("mouse:276", "playerctl next -p spotify")
bind_run("N", "playerctl next -p spotify")
bind_run("mouse_up", "playerctl volume 0.1- -p spotify")
bind_run("DOWN", "playerctl volume 0.1- -p spotify")
bind_run("mouse_down", "playerctl volume 0.1+ -p spotify")
bind_run("UP", "playerctl volume 0.1+ -p spotify")

--############################
--## ENVIRONMENT VARIABLES ###
--############################
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

--####################
--## LOOK AND FEEL ###
--####################

hl.config({
	general = {
		gaps_in = 1,
		gaps_out = 2,
		border_size = 1,
		col = {
			active_border = "rgb(d8647e)",
			inactive_border = "rgb(cdcdcd)",
		},
		resize_on_border = false,
		allow_tearing = false,
		layout = "master",
	},
	decoration = {
		rounding = 1,
		rounding_power = 2,
		active_opacity = 1,
		inactive_opacity = 1,
		shadow = {
			enabled = false,
		},
		blur = {
			enabled = false,
		},
	},
	animations = {
		enabled = false,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		new_status = "slave",
		mfact = 0.5,
	},
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		middle_click_paste = false,
		focus_on_activate = true,
	},
	cursor = {
		default_monitor = os.getenv("MAIN_DISPLAY"),
		no_warps = true,
	},
	group = {
		auto_group = false,
		col = {
			border_active = "rgb(bb9dbd)",
			border_inactive = "rgb(cdcdcd)",
		},
		groupbar = {
			enabled = false,
		},
	},
	input = {
		repeat_delay = 250,
		repeat_rate = 33,
		kb_layout = "pl,ua,us",
		kb_variant = ",phonetic,intl",
		kb_options = "grp:alt_caps_toggle",
		follow_mouse = 2,
		float_switch_override_focus = 0,
		sensitivity = -0.3,
		accel_profile = "flat",
	},
	xwayland = {
		force_zero_scaling = true,
	},
	render = {
		direct_scanout = 2,
	},
})

dofile("/etc/hypr/extra.lua")
