#!/usr/bin/env bash

execCommand=$1
className=$2

running=$(hyprctl -j clients | jq -r ".[] | select(.class == \"$className\")")

if [ "$running" ]; then
    hyprctl dispatch "hl.dsp.focus({window = 'class:$className'})"
else
    hyprctl dispatch "hl.dsp.exec_cmd('$execCommand')"
fi
