#!/usr/bin/env bash

SHELL_ORIG=$SHELL
SHELL="bash"

declare -a INDEXES=(
    "nixpkgs ctrl-j"
    "nixos ctrl-i"
    "noogle ctrl-h"
    "all ctrl-a"
)

OPEN_SOURCE_KEY="ctrl-s"
OPEN_HOMEPAGE_KEY="ctrl-o"
OPENER="xdg-open"

# bind_index binds the given $key to the given $index
bind_index() {
    local key="$1"
    local index="$2"

    local prompt=""
    local indexes_flag=""
    if [[ -n "$index" && "$index" != "all" ]]; then
        indexes_flag="--indexes $index"
        prompt=$index
    fi

    local preview="nix-search-tv preview $indexes_flag"
    local print="nix-search-tv print $indexes_flag"

    echo "$key:change-prompt($prompt> )+change-preview($preview {})+reload($print)"
}

STATE_FILE="/tmp/nix-search-tv-fzf"

# save_state saves the currently displayed index
# to the $STATE_FILE. This file serves as an external script state
# for communication between "print" and "preview" commands
save_state() {
    local index="$1"

    local indexes_flag=""
    if [[ -n "$index" && "$index" != "all" ]]; then
        indexes_flag="--indexes $index"
    fi

    echo "execute(echo $indexes_flag > $STATE_FILE)"
}

HEADER="$OPEN_HOMEPAGE_KEY - open homepage
$OPEN_SOURCE_KEY - open source
"

FZF_BINDS=""
for e in "${INDEXES[@]}"; do
    index=$(echo "$e" | awk '{ print $1 }')
    keybind=$(echo "$e" | awk '{ print $2 }')

    fzf_bind=$(bind_index "$keybind" "$index")
    fzf_save_state=$(save_state "$index")
    FZF_BINDS="$FZF_BINDS --bind '$fzf_bind+$fzf_save_state'"

    newline=$'\n'
    HEADER="$HEADER$keybind - $index$newline"
done

# reset the state
echo "" >/tmp/nix-search-tv-fzf

PREVIEW_WINDOW="wrap"
[ "$(tput cols)" -lt 90 ] && PREVIEW_WINDOW="$PREVIEW_WINDOW,up"

choice=$(eval "nix-search-tv print | fzf \
    --preview 'nix-search-tv preview \$(cat $STATE_FILE) {}' \
    --bind '$OPEN_SOURCE_KEY:execute(nix-search-tv source \$(cat $STATE_FILE) {} | xargs $OPENER)' \
    --bind '$OPEN_HOMEPAGE_KEY:execute(nix-search-tv homepage \$(cat $STATE_FILE) {} | xargs $OPENER)' \
    --layout reverse \
    --scheme path \
    --preview-window='$PREVIEW_WINDOW' \
    --header '$HEADER' \
    --header-first \
    --header-border \
    $FZF_BINDS
")

[[ -n "$choice" ]] && NIX_SHELL=1 SHELL=$SHELL_ORIG nix shell "nixpkgs#${choice#nixpkgs/ }"
