#!/usr/bin/env bash
filetype=$1
program=${2:-xdg-open}

declare -A files_dict
files=$(while read -r file; do
    echo "/${file#*/}"
done <<<"$(fd -t f -0 "$filetype\$" ~ | xargs -0 ls -lt)")

while read -r file; do
    basename=${file##*/}
    files_dict[$basename]=$file
done <<<"$files"
files=$(
    while read -r file; do
        echo "${file##*/}"
    done <<<"$files"
)

selection=$(echo "$files" | rofi -dmenu -p "$program") || exit 0

$program "${files_dict[$selection]}" &
