#!/usr/bin/env bash
filetype=$1
program=${2:-xdg-open}

declare -A files_dict
files=$(fd -t f -0 "$filetype\$" ~ | xargs -0 ls -lt | sed "s|^[^/]*||")

OIFS="$IFS"
IFS=$'\n'
for file in $files; do
    files_dict[$(basename "$file")]=$file
done
files=$(for file in $files; do
    basename "$file"
done)
IFS="$OIFS"

selection=$(echo "$files" | rofi -dmenu -p "$program") || exit 0

$program "${files_dict[$selection]}" &
