#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
        {
            fd -d 2 -t d . "$HOME/projects/" "$HOME/school/" "$HOME/.config/"
            echo "/etc/nixos"
            tmux list-sessions -F "#{session_name} (session)"
        } | sed "s|^$HOME/||" | fzf --tac
    )
    if [[ -n $selected ]]; then
        if [[ $selected == *" (session)" ]]; then
            selected_name="${selected% (session)}"
        elif [[ "${selected:0:1}" != / ]]; then
            selected="$HOME/$selected"
            selected_name=$(basename "$selected" | tr . _)
        else
            selected_name=$(basename "$selected" | tr . _)
        fi
    fi

fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)
inside_tmux=$(tmux display-message -p "#{client_pid}")

if [[ -z $inside_tmux ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $inside_tmux ]]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
